name: Markdown lint

on:
  workflow_dispatch:

jobs:
  markdown-link:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
    - name: Extract branch name
      run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
      id: extract_branch
    - name: Lint
      run: make markdown-lint
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        config-file: .github/workflows/markdown-link-check-config.json
        use-quiet-mode: yes
